package com.example.data

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class ProviderProfile(
    val id: String,
    val email: String? = null,
    @SerialName("company_name") val companyName: String,
    val description: String? = null,
    val phone: String? = null,
    val website: String? = null
)

@Serializable
data class DBSupportService(
    val id: String? = null, // autogenerated by Supabase
    @SerialName("provider_id") val providerId: String,
    val name: String,
    val description: String,
    val status: String = "Active",
    val category: String? = null,
    val latitude: Double? = null,
    val longitude: Double? = null
)

@Serializable
data class DBCoordinationRequest(
    val id: String? = null, // autogenerated by Supabase
    @SerialName("provider_id") val providerId: String,
    @SerialName("client_name") val clientName: String,
    @SerialName("service_name") val serviceName: String,
    val status: String = "Pending",
    @SerialName("contact_info") val contactInfo: String? = null,
    val notes: String? = null
)
